// <auto-generated />
using System;
using ApiRest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRest.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230611075616_SolucionDeProblemaConRequired")]
    partial class SolucionDeProblemaConRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("surnames")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            age = 18,
                            creationDate = new DateTime(2023, 6, 11, 9, 56, 16, 776, DateTimeKind.Local).AddTicks(2632),
                            email = "phernancamino@insllica.cat",
                            imageUrl = "",
                            name = "Pol",
                            password = "Alumne1234.",
                            surnames = "Hernan Camino",
                            updateDate = new DateTime(2023, 6, 11, 9, 56, 16, 776, DateTimeKind.Local).AddTicks(2682),
                            username = "polhernan"
                        },
                        new
                        {
                            Id = 2,
                            age = 18,
                            creationDate = new DateTime(2023, 6, 11, 9, 56, 16, 776, DateTimeKind.Local).AddTicks(2687),
                            email = "vlainezliso@insllica.cat",
                            imageUrl = "",
                            name = "Veronica",
                            password = "Alumne1234.",
                            surnames = "Lainez Liso",
                            updateDate = new DateTime(2023, 6, 11, 9, 56, 16, 776, DateTimeKind.Local).AddTicks(2689),
                            username = "vero"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
